{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ai-answer-assistant",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-answer-assistant-1.0.0.aar",
          "url": "android-ai-answer-assistant-1.0.0.aar",
          "size": 34290,
          "sha512": "38a2c55591685987829a216f5a082ceb22af9ff4b2d13ce4a69e1a8bc7f2e4eb594be1d002e0b43c0c764786970b00573524497ab63c8fbbcc74cb6ccd1c8c5e",
          "sha256": "ceb502e4890d45a70ff52051f19e684456fd716bb0bd1239ed47d848457b407a",
          "sha1": "268a1010851ebd8bfc4d8fac5bc1f560b65acf5e",
          "md5": "92057f3b22e7032e9367314404c9eae1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-answer-assistant-1.0.0.aar",
          "url": "android-ai-answer-assistant-1.0.0.aar",
          "size": 34290,
          "sha512": "38a2c55591685987829a216f5a082ceb22af9ff4b2d13ce4a69e1a8bc7f2e4eb594be1d002e0b43c0c764786970b00573524497ab63c8fbbcc74cb6ccd1c8c5e",
          "sha256": "ceb502e4890d45a70ff52051f19e684456fd716bb0bd1239ed47d848457b407a",
          "sha1": "268a1010851ebd8bfc4d8fac5bc1f560b65acf5e",
          "md5": "92057f3b22e7032e9367314404c9eae1"
        }
      ]
    }
  ]
}
