{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ai-editing-assistant",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-editing-assistant-2.1.0.aar",
          "url": "android-ai-editing-assistant-2.1.0.aar",
          "size": 42735,
          "sha512": "ce896958881c12db5d60eb8b41c828e3beefa0b958642e1407c8f50e744a1c2258ca271700fc3233beb25ae9209dba57a0baf6c45cee421a81a9ab97cbc898e6",
          "sha256": "5221116f728e150e4c6b411218c07a9049aa6df4593f78eb2ee6d16f772f031f",
          "sha1": "9b3b14ca3518ae14b51a3cf201624934671062b6",
          "md5": "a96946095258eaf2988651a9c9bb16ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-editing-assistant-2.1.0.aar",
          "url": "android-ai-editing-assistant-2.1.0.aar",
          "size": 42735,
          "sha512": "ce896958881c12db5d60eb8b41c828e3beefa0b958642e1407c8f50e744a1c2258ca271700fc3233beb25ae9209dba57a0baf6c45cee421a81a9ab97cbc898e6",
          "sha256": "5221116f728e150e4c6b411218c07a9049aa6df4593f78eb2ee6d16f772f031f",
          "sha1": "9b3b14ca3518ae14b51a3cf201624934671062b6",
          "md5": "a96946095258eaf2988651a9c9bb16ea"
        }
      ]
    }
  ]
}
