{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ai-translate",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-translate-1.0.0.aar",
          "url": "android-ai-translate-1.0.0.aar",
          "size": 34417,
          "sha512": "ee48b3417c0b8a4332b45de766834fedce9133abd9b4f0be7ca2f68d58f51853c846ef0341e289ab8d33248f4335a8b07863028ce2b32fd0a5b0ccc97c233644",
          "sha256": "6f61324acb58bdcf0bf0932b713333c2bd80365b05f4986942354a84d6664ac2",
          "sha1": "514c44b2ea168611b061c30de249a01b036b31f7",
          "md5": "4a4f28e8b742978ad8fc52137ae30f4b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-translate-1.0.0.aar",
          "url": "android-ai-translate-1.0.0.aar",
          "size": 34417,
          "sha512": "ee48b3417c0b8a4332b45de766834fedce9133abd9b4f0be7ca2f68d58f51853c846ef0341e289ab8d33248f4335a8b07863028ce2b32fd0a5b0ccc97c233644",
          "sha256": "6f61324acb58bdcf0bf0932b713333c2bd80365b05f4986942354a84d6664ac2",
          "sha1": "514c44b2ea168611b061c30de249a01b036b31f7",
          "md5": "4a4f28e8b742978ad8fc52137ae30f4b"
        }
      ]
    }
  ]
}
