{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ai-answer-assistant",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-answer-assistant-1.0.1.aar",
          "url": "android-ai-answer-assistant-1.0.1.aar",
          "size": 34573,
          "sha512": "d8911a6ea56f62f7ef7a24c01fb900e56a872e6c2e1aa1da114e042e20f9af5de4b91b5ece5a0a38f2bc9e557bfa9bd9b97994d22f575ba008e058287f59a07f",
          "sha256": "60acf777d33c3c5b3a2ae570dc796ff3c8b51989b899a53316a66fedc9899708",
          "sha1": "cf0e3fec38bb7c418d989264df323546856b4b1f",
          "md5": "21c2a4eefcd6e8eb1707e2cad9da7df4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-answer-assistant-1.0.1.aar",
          "url": "android-ai-answer-assistant-1.0.1.aar",
          "size": 34573,
          "sha512": "d8911a6ea56f62f7ef7a24c01fb900e56a872e6c2e1aa1da114e042e20f9af5de4b91b5ece5a0a38f2bc9e557bfa9bd9b97994d22f575ba008e058287f59a07f",
          "sha256": "60acf777d33c3c5b3a2ae570dc796ff3c8b51989b899a53316a66fedc9899708",
          "sha1": "cf0e3fec38bb7c418d989264df323546856b4b1f",
          "md5": "21c2a4eefcd6e8eb1707e2cad9da7df4"
        }
      ]
    }
  ]
}
