{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ai-editing-assistant",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-editing-assistant-1.0.0.aar",
          "url": "android-ai-editing-assistant-1.0.0.aar",
          "size": 39590,
          "sha512": "04c72d18f1f7f67ab8a2d1895e94b30751c612671ab51ba88a49dcac150cb6afd405306b1eedc8410d216a29948203a807fe56229c834d4d157a5e0397627bcb",
          "sha256": "799914bafcca2a2f6601bc19e3c7d66b6bf46fef25d637ac2dde42e2cda8db8f",
          "sha1": "035aeda5a34f6415d3467e098be76192c5ff6bc8",
          "md5": "ecb541b8607c1d101b963e1363ff3b11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-editing-assistant-1.0.0.aar",
          "url": "android-ai-editing-assistant-1.0.0.aar",
          "size": 39590,
          "sha512": "04c72d18f1f7f67ab8a2d1895e94b30751c612671ab51ba88a49dcac150cb6afd405306b1eedc8410d216a29948203a807fe56229c834d4d157a5e0397627bcb",
          "sha256": "799914bafcca2a2f6601bc19e3c7d66b6bf46fef25d637ac2dde42e2cda8db8f",
          "sha1": "035aeda5a34f6415d3467e098be76192c5ff6bc8",
          "md5": "ecb541b8607c1d101b963e1363ff3b11"
        }
      ]
    }
  ]
}
