{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ai-translate",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-translate-2.0.0.aar",
          "url": "android-ai-translate-2.0.0.aar",
          "size": 44756,
          "sha512": "f06b4afc907dc78f6218f3bdfa1862ef3a44a7b93d65ee8e525d6a2d637fb4b8d84f7a01a9b911cc73450d79412881ba31ccd9ca5c5d9eca456e9b74122f6b71",
          "sha256": "278993febd56ef1ed597ef15b4c85fc2aab3d78a8e8f7d46e7f886a7f787c061",
          "sha1": "341d84cd7bdb64f43964839711e9a5ba1bc0c7ec",
          "md5": "8e20886cf1a2bd89c2f876b5d0211bf7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ai-translate-2.0.0.aar",
          "url": "android-ai-translate-2.0.0.aar",
          "size": 44756,
          "sha512": "f06b4afc907dc78f6218f3bdfa1862ef3a44a7b93d65ee8e525d6a2d637fb4b8d84f7a01a9b911cc73450d79412881ba31ccd9ca5c5d9eca456e9b74122f6b71",
          "sha256": "278993febd56ef1ed597ef15b4c85fc2aab3d78a8e8f7d46e7f886a7f787c061",
          "sha1": "341d84cd7bdb64f43964839711e9a5ba1bc0c7ec",
          "md5": "8e20886cf1a2bd89c2f876b5d0211bf7"
        }
      ]
    }
  ]
}
